FROM intel/oneapi-basekit:2025.0.2-0-devel-ubuntu22.04

# Install common dependencies and netlib
COPY --from=base:latest /usr /usr

# Install common dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    wget \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy the project files
COPY . .

# Build and install the project
RUN bash -c "source /opt/intel/oneapi/setvars.sh && mkdir build && cd build && cmake .. && make && make install"
