name: "Coverity Scan"
permissions: read-all

# Trigger for PR an merge to develop branch
on:
  push:
    branches: develop
  pull_request:
  workflow_dispatch:

jobs:
  onemkl-coverity:
    runs-on: ubuntu-latest
    # One runner for each domain
    strategy:
      matrix:
        domain: [blas, dft, lapack, rng]
    name: MKL ${{ matrix.domain }} CPU
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - name: Install oneapi
      uses: rscohn2/setup-oneapi@2ad0cf6b74bc2426bdcee825cf88f9db719dd727 # v0.1.0
      with:
        components: |
          icx@2024.1.0
          mkl@2024.1.0
    - name: Get Coverity Scan Tool
      run: |
        curl https://scan.coverity.com/download/cxx/linux64 --no-progress-meter --output cov-analysis.tar.gz --data "token=${{ secrets.COVERITY_SCAN_TOKEN }}&project=vmalia%2FoneMKL"
        tar -xf cov-analysis.tar.gz
    - name: Get current date and time
      id: dt
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYYMMDD_HHmmss"
    - name: Configure & build with Coverity
      run: |
        source /opt/intel/oneapi/setvars.sh
        cmake -DENABLE_MKLGPU_BACKEND=off -DTARGET_DOMAINS=${{ matrix.domain }} -DCMAKE_VERBOSE_MAKEFILE=on -DBUILD_FUNCTIONAL_TESTS=False -B build_cov
        cov-analysis-linux64-2023.6.2/bin/cov-configure --template --comptype intel_icx --compiler icx
        cov-analysis-linux64-2023.6.2/bin/cov-configure --template --comptype intel_icpx --compiler icpx
        cov-analysis-linux64-2023.6.2/bin/cov-build --dir cov-int cmake --build build_cov/ --target all --parallel
        zip -r onemkl-interfaces-${{ matrix.domain }}.zip cov-int/
        curl --form token=${{ secrets.COVERITY_SCAN_TOKEN }} \
              --form email=viraj.malia@intel.com \
              --form file=@onemkl-interfaces-${{ matrix.domain }}.zip \
              --form version="Version" \
              --form description="Description" \
              https://scan.coverity.com/builds?project=vmalia%2FoneMKL
