name: "Coverity Scan"
permissions: read-all

# Trigger for PR an merge to develop branch
on:
  push:
    branches: develop
  pull_request:
  workflow_dispatch:

jobs:
  onemkl-coverity:
    runs-on: ubuntu-latest
    # One runner for each domain
    strategy:
      matrix:
        domain: [blas, dft, lapack, rng]
    name: MKL ${{ matrix.domain }} CPU
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - name: Install oneapi
      uses: rscohn2/setup-oneapi@2ad0cf6b74bc2426bdcee825cf88f9db719dd727 # v0.1.0
      with:
        components: |
          icx@2024.1.0
          mkl@2024.1.0
    - name: Configure for a domain
      run: |
        source /opt/intel/oneapi/setvars.sh
        cmake -DENABLE_MKLGPU_BACKEND=off -DTARGET_DOMAINS=${{ matrix.domain }} -DCMAKE_VERBOSE_MAKEFILE=on -DBUILD_FUNCTIONAL_TESTS=False -B build
    - name: Coverity Scan
      uses: vapier/coverity-scan-action@v1
      with:
        email: 'viraj.malia@intel.com'
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
        working-directory: 'build'
        description: 'Coverity Scan Description'
        command: 'cmake --build . --target all --parallel'
