name: "Coverity Scan"
permissions: read-all

# Trigger for PR an merge to develop branch
on:
  push:
    branches: develop
  pull_request:
  workflow_dispatch:

jobs:
  onemkl-coverity:
    runs-on: ubuntu-latest
    # One runner for each domain
    strategy:
      matrix:
        domain: [blas, dft, lapack, rng]
    name: MKL ${{ matrix.domain }} CPU
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - name: Install oneapi
      uses: rscohn2/setup-oneapi@2ad0cf6b74bc2426bdcee825cf88f9db719dd727 # v0.1.0
      with:
        components: |
          icx@2024.1.0
          mkl@2024.1.0
    - name: Configure & build a domain
      run: |
        source /opt/intel/oneapi/setvars.sh
        cmake -DENABLE_MKLGPU_BACKEND=off -DTARGET_DOMAINS=${{ matrix.domain }} -DCMAKE_VERBOSE_MAKEFILE=on -DBUILD_FUNCTIONAL_TESTS=False -B build_cov
        cmake --build build_cov/ --target all --parallel
    - name: Setup Coverity Scan Tool
      run: |
        wget https://scan.coverity.com/download/cxx/linux64 --post-data "token=${{ secrets.COVERITY_SCAN_TOKEN }}" -O coverity_tool.tgz
        tar -xf coverity_tool.tgz
        export PATH=$PWD/coverity_tool/bin/:$PATH
    - name: Run Coverity Scan Tool
      run: |
        cov-config --comptype clang --compiler icx
        cov-build --dir cov-int cmake --build build_cov/ --target all --parallel
