name: oneMKL Interfaces CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_n_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build oneMKL
      run: |
        docker build . --file Dockerfile.ci --tag onemkl_0.2
        docker run onemkl_0.2
